### ISSUE TITLE
document recommended compiler 

### ISSUE THREAD

**Issue by caseyjlaw** [ledatelescope/bifrost#106]
I'm trying to build at the NRAO, but they have a relatively old g++. It fails when trying with the flag `-std=c++11`. Seems that is only supported for g++ after 4.6 (https://stackoverflow.com/questions/10363646/compiling-c11-with-g).
Can you document some recommendations on compilers that have been tested?

**Comment by benbarsdell** [comment]
We may have only tested with Ubuntu 14.04 (gcc 4.8) and later. I can try building against older versions when I have a chance and will document what I find.

What version of g++ is actually available at NRAO? (Also, what CUDA version?). Supporting C++98 in Bifrost will probably not be possible at this stage, but there may be some ways to work around it.

**Comment by caseyjlaw** [comment]
They seem to use 4.4.7 as default on RHEL6.8.
I have installed 4.8.5 via anaconda. I'll see what I can do.
Some coverage would help, but a quick note in the docs was all I hoped for.

**Comment by MilesCranmer** [comment]
Hi @caseyjlaw, thanks for pointing this out! I have added a note to the docs.

Cheers,
Miles
