### ISSUE TITLE
__builtin_ia32_mwaitx undefined

### ISSUE THREAD

**Issue by sherandoresearch** [ledatelescope/bifrost#108]
I am on Ubuntu 16.04 using gcc 5.3 and CUDA 7.5 and get the error that __builtin_ia32_mwaitx is undefined. I have not made any changes to the user.mk file except to GPU_ARCHS line. Is there a recommended version of CUDA and gcc? Thanks

**Comment by sherandoresearch** [comment]
Updated to CUDA 8 (9 seems too new for now). Will post results here.

**Comment by MilesCranmer** [comment]
Hi @sherandoresearch, strange that this didn't work. What was the full error? Was it during the install or test stage?

I have also had some problems with CUDA versions less than 8 in the past. It's good to hear that CUDA 8 is now working for you.

I have also just added a note about this in the docs, thanks for letting us know.
