### ISSUE TITLE
How to realize coherent de-dispersion of Pulsar signal in Bifrost?

### ISSUE THREAD

**Issue by zyfcharm** [ledatelescope/bifrost#125]
Dear Scholar, because of the recent research on the coherent de-dispersion of pulsars, I want to implement the coherent de-dispersion Algorithm of pulsars on Bifrost, but I don't know how to implement it on the basis of the existing package of Bifrost. Sincerely request your guidance，thanks
                                                                                                                         yanfei

**Comment by telegraphic** [comment]
Hi @zyfcharm, this is quite open ended, so hard to give specific advice. But first, _you need to have  code that does coherent dedispersion_. That is, you need to write a _dedispersion kernel_, in either Python or C/CUDA. This paper may be a good start - https://arxiv.org/abs/1607.00909.

Then you would need to make a `TransformBlock`, [see tutorial here](http://ledatelescope.github.io/bifrost/your-first-blocks.html#your-first-blocks), that calls your dedispersion kernel in the `on_data()` block.

**Comment by zyfcharm** [comment]
I thank you sincerely for your guidance. Your guidance is of great significance to me. I will experiment with your guidance. Thanks again
