### ISSUE TITLE
About UDP block

### ISSUE THREAD

**Issue by Leeying1235** [ledatelescope/bifrost#131]
Hello,
I got some problems when i use UDP blocks you provided .
### Problems

> Is there any examples to show how to use this block?

> The package format of mine is different from yours, does it means that i can not use this block? If it does,what can i do to fix it  and how?

> If i just want to capture UDP package as source,how can i make it?

Looking forward to your reply!
Lee

**Comment by jaycedowell** [comment]
> Is there any examples to show how to use this block?

You can find an example of how udp_capture can be used in a pipeline here:

https://github.com/epic-astronomy/EPIC/blob/master/LWA/LWA_bifrost.py

The `FEngineCaptureOp` class is the one that calls/wraps udp_capture.

> The package format of mine is different from yours, does it means that i can not use this block? If it does,what can i do to fix it and how?

Currently the only packet format supported in the main bifrost repo is the CHIPS format.  You could either modify what is current there or you could look at my fork here:

https://github.com/jaycedowell/bifrost/tree/disk-readers

which provides an abstraction layer for adding in different packet formats.

> If i just want to capture UDP package as source,how can i make it?

I'm not sure I understand the question.

**Comment by Leeying1235** [comment]
Ok ,thank you for your reply .And i have browsed the examples you given. It helps me a lot.
The last questions i mentioned means i just want to capture UDP package with UdpCapture block .
But after i knew the message you provided , i think i could not use this block directly ,some changes should be done. And my questions have been solved ,i will close this issue.
Sincerely thank you  @jaycedowell  again.
