### ISSUE TITLE
bifrost user/developer meeting?

### ISSUE THREAD

**Issue by telegraphic** [ledatelescope/bifrost#140]
Hi all -- hope you are all safe and well. Trusting this issue pings the emails of all interested parties!

I just had a look at the pull requests and think there's a lot of exciting activity going on (Jayce has been busy!). Would anyone be interested in a zoom meeting in the coming weeks to chat about future work?

As a small update: I have been using bifrost at Molonglo for the UTMOST-2D upgrade (an FRB localisation project). So far the pipelines have been little scripts for instrument testing and development, or passing files through a GPU pipeline, and bifrost has been very useful. Most of the work is a bit hacky and not that useful for other people, but I wrote a simple correlator kernel using the `dp4a` instruction (only works for N<=32 at the moment), and am halfway through porting Ewan Barr's beanfarmer code (GPU beamformer code).

**Comment by jaycedowell** [comment]
I'd be interested in some form of meeting

**Comment by jaycedowell** [comment]
We now have monthly meetings.
