### ISSUE TITLE
Problems encountered while installing and running 'make -j'

### ISSUE THREAD

**Issue by yushilingco** [ledatelescope/bifrost#154]
$ make -j
udp_capture.cpp:87:32: fatal error: mellanox/vma_extra.h: No such file or directory
compilation terminated.
autodep.mk:32: recipe for target 'udp_capture.o' failed
make[1]: *** [udp_capture.o] Error 1
...
ptxas /tmp/tmpxft_000029f6_00000000-7_fft.compute_35.ptx, line 2379; error   : Illegal operand type to instruction 'ld'
ptxas /tmp/tmpxft_000029f6_00000000-7_fft.compute_35.ptx, line 2379; error   : Unknown symbol '__unnamed_1_param_0'
ptxas /tmp/tmpxft_000029f6_00000000-7_fft.compute_35.ptx, line 2747; error   : Illegal operand type to instruction 'ld'
ptxas /tmp/tmpxft_000029f6_00000000-7_fft.compute_35.ptx, line 2747; error   : Unknown symbol '__unnamed_2_param_0'
ptxas fatal   : Ptx assembly aborted due to errors
autodep.mk:56: recipe for target 'fft.o' failed
make[1]: *** [fft.o] Error 255
make[1]: Leaving directory '/home/yushiling/software/bifrost/bifrost-master/src'
Makefile:15: recipe for target 'libbifrost' failed
make: *** [libbifrost] Error 2

I encountered the above problems during installation. I tried to install the missing package, but it seems incomplete. I hereby ask for the reason. Thank you very much.

**Comment by yushilingco** [comment]
I'm sorry I can't find GPU_ARCHS_VALID and GPU_ARCH_LATEST. And can you provide a configure for testing ？Thanks a lot.

**Comment by jaycedowell** [comment]
How GPU_ARCHS_VALID and GPU_ARCH_LATEST are defined is in `src/Makefile`.  All you should need to do is convert the make shell calls into normal shell calls.  Something like the following bash script:
```
#!/bin/bash

GPU_ARCHS=86
GPU_ARCHS_SUPPORTED=`nvcc -h | grep -Po "compute_[0-9]{2}" | cut -d_ -f2 | sort | uniq`
GPU_ARCHS_VALID=`echo "${GPU_ARCHS} ${GPU_ARCHS_SUPPORTED}" | xargs -n1 | sort | uniq -d | xargs`
GPU_ARCH_LATEST=`echo "${GPU_ARCHS_VALID}" | rev | cut -d' ' -f1 | rev`
echo "Supported: ${GPU_ARCHS_SUPPORTED}"
echo "Valid: ${GPU_ARCHS_VALID}"
echo "Latest: ${GPU_ARCHS_LATEST}"
```

For the `configure`test you'll need to checkout the repository with git and then switch from the master branch to autoconf to access it.

**Comment by yushilingco** [comment]
The results are as follows:
Supported: 30
32
35
37
50
52
53
60
61
62
70
72
75
80
86
Valid: 86
Latest:

**Comment by jaycedowell** [comment]
The only other thing I can suggest is that you modify `src/Makefile` and explicitly set GPU_ARCHS_VALID and GPU_ARCH_LATEST to 86 instead of the shell calls that are in there now.

**Comment by yushilingco** [comment]
Thank you for your advice. I want to check whether the contents in the user.mk file are correct.
Can you tell me what the vacancy item represents? Thank you!
CXX           ?= g++
NVCC          ?= nvcc
LINKER        ?= g++
CPPFLAGS      ?=
CXXFLAGS      ?= -O3 -Wall -pedantic
NVCCFLAGS     ?= -O3 -Xcompiler "-Wall" #-Xptxas -v
LDFLAGS       ?=
DOXYGEN       ?= doxygen
PYBUILDFLAGS   ?=

**Comment by jaycedowell** [comment]
Nothing, i.e., no additional flags are specified.

**Comment by yushilingco** [comment]
It means it doesn't need to be modified and there's no problem, right？

**Comment by jaycedowell** [comment]
No, these shouldn't need to be modified.

**Comment by yushilingco** [comment]
I am eager to use this framework to realize the real-time processing function, but because I have failed to compile many times, the installation is unsuccessful, and I can't use it further, so I take the liberty to ask you whether you can provide the successfully installed ISO image file？Thank you very much!

**Comment by jaycedowell** [comment]
You can always try our Docker containers or AWS images.  The instructions for them can be found here:  https://github.com/ledatelescope/bifrost_tutorial

Did you try building from the autoconf branch?

**Comment by yushilingco** [comment]
Thank you. Yes, I don't know exactly what to do. If it's convenient for you, can you tell me how to do it~

**Comment by jaycedowell** [comment]
Sure, try a:
```
git clone https://github.com/ledatelescope/bifrost.git bifrost_autoconf
cd bifrost_autoconf
git checkout autoconf
./configure
```

**Comment by yushilingco** [comment]
That's great, but I can't import successfully：
>>> import bifrost
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yushiling/anaconda3/lib/python3.8/site-packages/bifrost/__init__.py", line 37, in <module>
    from bifrost import core, memory, affinity, ring, block, address, udp_socket
  File "/home/yushiling/anaconda3/lib/python3.8/site-packages/bifrost/core.py", line 32, in <module>
    from bifrost.libbifrost import _bf
  File "/home/yushiling/anaconda3/lib/python3.8/site-packages/bifrost/libbifrost.py", line 41, in <module>
    import bifrost.libbifrost_generated as _bf
  File "/home/yushiling/anaconda3/lib/python3.8/site-packages/bifrost/libbifrost_generated.py", line 816, in <module>
    _libs["bifrost"] = load_library("bifrost")
  File "/home/yushiling/anaconda3/lib/python3.8/site-packages/bifrost/libbifrost_generated.py", line 541, in __call__
    raise ImportError("Could not load %s." % libname)
ImportError: Could not load bifrost.

**Comment by yushilingco** [comment]
When I run the a simple pipeline example, an error is reported：
File "/home/yushiling/anaconda3/envs/learn/lib/python2.7/site-packages/bifrost/blocks/transpose.py", line 73, in on_data
    bf.transpose.transpose(ospan.data, ispan.data, self.axes)
AttributeError: 'module' object has no attribute 'transpose'

**Comment by jaycedowell** [comment]
It's good to hear that you were able to build and install using the autoconf branch.  I think the most recent `bf.transpose.transpose` error is a bug in the Python high level blocks.

**Comment by yushilingco** [comment]
Is there any solution?

**Comment by jaycedowell** [comment]
Try applying the changes in this commit:   https://github.com/ledatelescope/bifrost/pull/153/commits/8c035685985a5a419cda851831df8fba0364130d

**Comment by yushilingco** [comment]
Thank you very much. I've looked for it, but I seem to have missed this information. I'll try it.

**Comment by yushilingco** [comment]
Can I ask you how to receive UPD packets in real time and copy them to GPU for operation?

**Comment by jaycedowell** [comment]
At this point you should take a look at the Bifrost tutorials:  https://github.com/ledatelescope/bifrost_tutorial

Any additional questions or problems you have that are not related to installation should be submitted as new issues.

**Comment by yushilingco** [comment]
OK, I see. Thank you again for your patience. I have no problem with the installation now!

**Comment by jaycedowell** [comment]
Closing with the release of v0.10.0.
