### ISSUE TITLE
pkgconfig file for bifrost

### ISSUE THREAD

**Issue by telegraphic** [ledatelescope/bifrost#160]
I just discovered that the package management system on our HPC cluster created this `bifrost.pc` pkgconfig file:

```
prefix=/group/director2183/dancpr/software/centos7.6/apps/cascadelake/gcc/8.3.0/bifrost/0.0.2
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: bifrost
Description: A stream processing framework for high-throughput applications.
Requires:
Version: 0.9.0
Libs: -L${libdir} -lbifrost
Cflags: -I${includedir}
```

If `bifrost.pc` can be found in the env variable `PKG_CONFIG_PATH` then build systems will be able to figure out what flags to add. Given it looks pretty simple to generate, I suggest that `bifrost.pc` would be a nice addition to bifrost. (will be particularly useful when compiling plugins)

**Comment by jaycedowell** [comment]
It's already part of `autoconf`.  It just needs some testing to see if/how well it works.

**Comment by telegraphic** [comment]
Excellent! (in that case maybe autoconf generated it)

**Comment by jaycedowell** [comment]
In a similar vein there is also a `bifrost.m4` file to help other autotools-based packages find Bifrost if they need it.
