### ISSUE TITLE
PipelineContext does not exist inside pipeline.py

### ISSUE THREAD

**Issue by ProfundityOfScope** [ledatelescope/bifrost#197]
When calling Pipeline.as_default(), and error is thrown as the returned object (PipelineContext) is not defined.

**Comment by jaycedowell** [comment]
[f780ec0](https://github.com/ledatelescope/bifrost/commit/f780ec0164c753d5a99d45ea615c4b37ec3ec327) should help with this.  I'm not sure if we want to append or replace what goes into the thread local storage.
