### ISSUE TITLE
New DeprecationWarnings in cuda 12.4

### ISSUE THREAD

**Issue by dentalfloss1** [ledatelescope/bifrost#239]
A large number of DeprecationWarnings are generated when using "make" to build bifrost. Fortunately most of the warnings seem to limited to transpose.cu. See attached log of the make command.
[makelog.txt](https://github.com/user-attachments/files/15933900/makelog.txt)

**Comment by jaycedowell** [comment]
Looks like the main culprit is:
```
warning: ‘cudaError_t 
   cudaDeviceSetSharedMemConfig(cudaSharedMemConfig)’ is deprecated [
   -Wdeprecated-declarations]
```
I found [this on SO](https://stackoverflow.com/questions/78211209/cudafuncsetsharedmemconfig-is-deprecated-in-12-4-why) which indicates that there isn't a replacement and that it really doesn't matter.  If we are concerned about it we can wrap it with some kind of THIS_IS_OLD_CUDA macro.
