### ISSUE TITLE
sequence header should be returned as python dict

### ISSUE THREAD

**Issue by telegraphic** [ledatelescope/bifrost#24]
At the moment the header appears as a `np.ndarray` with `dtype=uint8`, so you have to convert it back using

```
header = json.loads(iseq.header.tostring())
```

can `ring.read()` return `iseq` with `iseq.header` as a dictionary? Looking at the `ring.py` code I have NFI how this would be implemented...

**Comment by benbarsdell** [comment]
This is addressed by the new pipeline code, which assumes headers are always json format and returns a dict (specifically https://github.com/ledatelescope/bifrost/blob/master/python/bifrost/ring2.py#L157).
