### ISSUE TITLE
Choice of build tools

### ISSUE THREAD

**Issue by MilesCranmer** [ledatelescope/bifrost#25]
I will try implementing some type of automated build tool for Jenkins to run on `feature/automated-testing`. Currently I have heard the best reviews for cmake, so I will use that for now. I am interested to hear everyone's opinions on the matter.
[This list gives a good run down on many different options.](https://bitbucket.org/scons/scons/wiki/SconsVsOtherBuildTools#markdown-header-make)

**Comment by benbarsdell** [comment]
I think this can be closed for now. The current Makefile-based system seems to be working well for the scope of the project. Feel free to re-open if anyone disagrees :)

**Comment by telegraphic** [comment]
agreed!
