### ISSUE TITLE
Numpy-based unit tests and example pipelines

### ISSUE THREAD

**Issue by telegraphic** [ledatelescope/bifrost#40]
I think that transparent movement of numpy data will be a killer bifrost feature. Here's a list of unit tests / good examples that I propose we develop.  These may inform the Python API too: it should be logical and easy to implement pipelines that do these sorts of things.
### Tests / examples
- Transfer a **single** numpy array + header from a source -> sink. Verify data integrity using a checksum in the header (i.e. data can be inferred from header + some a priori info). For these tests, gulp size is equal on both source and sink.
  1. Data array size equal to gulp size
  2. Data array size smaller than gulp size
  3. Data array size greater than gulp size.
- Transfer a **single** numpy array + header from a source -> task -> sink. Equal gulp sizes on all rings.
  1. Data array size equal to gulp size
  2. Data array size smaller than gulp size
  3. Data array size greater than gulp size.
- Transfer a **stream** of numpy arrays + headers from a source to a sink. Equal gulp sizes on all rings.
  1. Sequence size equal to gulp size
  2. Sequence size smaller than gulp size
  3. Sequence size greater than gulp size
- Transfer a **stream** of numpy arrays + headers from a source -> task -> sink. Equal gulp sizes on all rings.
  1. Sequence size equal to gulp size
  2. Sequence size smaller than gulp size
  3. Sequence size greater than gulp size
- Transfer a **stream** of numpy arrays + headers from a sink to source, with different gulp sizes on the ring read and writes.
- Generate a large numpy array and save it to file. Treat this is a streaming data source, stream as numpy arrays between a file-reading source block and a file-writing sink block. Compare the two files by MD5 checksum, then delete both files.
### A simple checksum

Have a value in the header `{'checksum': 1234}`, which can be used to generate a numpy data array. For example, a the checksum could just be an additive offset on a `np.arange`:

``` python
self.header = {'dtype' : 'float32', 
     'shape' : (1024,), 
     'checksum' : 1729 

self.data = np.arange(0, self.header['shape'][0], 1, dtype = self.header['dtype']) 
self.data += self.header['checksum']
```

**Comment by jaycedowell** [comment]
Both are part of the current version of Bifrost.
