### ISSUE TITLE
Use case: gpuspec for Breakthrough Listen

### ISSUE THREAD

**Issue by telegraphic** [ledatelescope/bifrost#51]
For Breakthrough Listen, we need a real-time pipeline for generation of spectral data from voltage data.

At the moment, we have a lot of data stored in `guppi raw` format, and need to convert this when not observing into spectra. We are currently using a big, messy C/CUDA code called `gpuspec`; I would like to recreate this using bifrost.

I have created an example python script using `PyCuda` and `scikit cuda`, which is a load quicker than regular python, but still pretty slow. Essentially, I'm just using cuFFT and a cuda multiply. The two slowest parts of the code seem to be file reading, memcopies to/from device, and the numpy fftshift function (is there a CUDA one??).

As the memcopy/file read is the slowest part, this seems ripe for pipelining. However, I'm not sure where to start. Advice / boilerplate appreciated! 

### Getting example code

Clone the filterbank repository with the `gpuspec.py` code in it:

```sh
git clone https://github.com/ucBerkeleySETI/filterbank
```
Get some data from public data archive (http://www.breakthroughinitiatives.org/OpenDataSearch)

```
wget http://blpd0.ssl.berkeley.edu/ratan/blc05_guppi_57628_20146_DIAG_HIP88194_0008.0001.raw
```

### Running example code

Run `gpuspec` code:
```
./gpuspec.py blc05_guppi_57628_20146_DIAG_HIP88194_0008.0001.raw -N 5 -f 1024
```

Output shows some benchmarking:
```
Integration ID:	 0 (1 of 5)
(Data load:		 0.07s)
FFT Plan:		   0.18s

XX polarization timing
    ..memcopy to gpu:     0.24s
    ..cuFFT:              0.00s
    ..memcopy from gpu:   0.06s
    ..cuMultiply:         0.20s
cuFFT total:			  0.93s
DC blanking:              0.00s
FFT shift:                0.62s
Accumulate:               0.04s

Integration ID:	 0 (2 of 5)
(Data load:		 0.07s)
XX polarization timing
    ..memcopy to gpu:     0.24s
    ..cuFFT:              0.00s
    ..memcopy from gpu:   0.05s
    ..cuMultiply:         0.06s
cuFFT total:			  0.85s
DC blanking:              0.00s
FFT shift:                0.51s
Accumulate:               0.04s
```

**Comment by telegraphic** [comment]
FYI, my code for this is in
https://github.com/telegraphic/bifrost/tree/master/gpuspec

It works in that it takes an input, does all the operations, and puts out an output, but there is some data corruption going on somewhere. Nevertheless, it looks vaguely correct which is somewhat reassuring.

**Comment by telegraphic** [comment]
(also note some extra cuda kernels in tree/master/src)

**Comment by benbarsdell** [comment]
Hey Danny, two quick questions re guppi raw format:

1. Which header parameters can be used to derive the exact time the observation was made?
2. Could the headers ever change within a single file?

**Comment by benbarsdell** [comment]
@telegraphic 
Nvm about (1), I got it from looking in the dspsr source: PKTIDX*PKTSIZE gives the byte offset, and STT_IMJD + STT_SMJD/8600. gives the starting MJD.

**Comment by benbarsdell** [comment]
https://github.com/ledatelescope/bifrost/commit/88101a971d2af39727955d231c7187c78a48e5dc adds DetectBlock and FftShiftBlock, which are relevant to this issue.

**Comment by benbarsdell** [comment]
@telegraphic do you have an update on the status of this use-case?

A relatively complete example of this pipeline was added in https://github.com/ledatelescope/bifrost/commit/eaf1a93d05ae2f699113dc89460d4e697f65e5a1.

**Comment by telegraphic** [comment]
I think it's fair to close this issue at this stage! bifrost is being used in places within Breakthrough Listen, but rawspec code (https://github.com/UCBerkeleySETI/rawspec) also being used
