### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by MilesCranmer** [ledatelescope/bifrost#54]
Hi all,
I'll be cleaning up the repo over the next few days. Unmerged branches will be cleaned of old code/unused tests/other files, and then merged once unit tests pass. Pull requests will be submitted for each of these branches. Some issues will be closed or moved.
After this, I'll start adapting some things (incl. numpyblock, unit tests, etc.) to Ben's TF syntax, and then we can work to merge that branch. 

I may write some more documentation during this process or after, depending on how much I think things will change with the new syntax/pipeline structure.

Let me know if you have any ideas to help with this process.
Cheers,
Miles

**Comment by benbarsdell** [comment]
Hi Miles,

Just wondering if you've made any local changes to the feature/new-pipeline (TF syntax) branch? I was thinking of just manually merging it into master in a non-destructive way (i.e., such that the existing block/pipeline code is unaffected). This will make it easier to develop alongside changes in master without having to continuously merge things.

I'd also be interested to hear about any other updates you have wrt this cleanup (there are some other things I'd like to merge that may conflict).

Cheers,

Ben

**Comment by MilesCranmer** [comment]
Hi Ben,

I have not made any local changes to the TF syntax branch. I am excited to see it merged into master. By the way, have you uploaded any of the code for bfMap yet? I would be interested in trying it. 

I have a few ongoing branch cleanups that I have yet to put up for a pull request. My original guess (as seen in this issue posting) was that this would take a few days. My estimate was inaccurate. Additionally, the Bifrost development I was planning to do over Christmas was postponed for ADP debugging, so I still have a lot to do in terms of cleaning.

Which additional things are you interested in merging? We can also talk about this at the telecon today.

Cheers,

Miles
