### ISSUE TITLE
More Python JIT compilation to remove API overhead

### ISSUE THREAD

**Issue by MilesCranmer** [ledatelescope/bifrost#60]
Barak Zackay convinced me to try [Numba](https://github.com/numba/numba). It is very easy and very fast. You tag a `@jit` decorator on pure python functions (which can use numpy arrays and methods inside), and Numba compiles them to the point where they are as [fast as C](https://www.ibm.com/developerworks/community/blogs/jfp/entry/A_Comparison_Of_C_Julia_Python_Numba_Cython_Scipy_and_BLAS_on_LU_Factorization?lang=en) and certainly faster than using pypy or another interpreter.
This is for the future, but it would be interesting if we were to rewrite some of the Python API using Numba. Apparently, there is also a way to compile pure python into CUDA kernels.

A drawback of using Numba is that it is difficult to install the module if you are not using Conda. There is also a lack of optimizer support for python types like dictionaries and lists.

**Comment by MilesCranmer** [comment]
CUDA kernels with numba: http://numba.pydata.org/numba-doc/dev/cuda/kernels.html

**Comment by caseyjlaw** [comment]
FWIW, I also hesitated to move my code (e.g., our rtpipe stuff) to the conda installer for a while. Numba and other pydata projects compelled me to do so. I'm happy I did!
