### ISSUE TITLE
Bifrost FFT in pipeline

### ISSUE THREAD

**Issue by telegraphic** [ledatelescope/bifrost#61]
Ok, I'm playing around with the bifrost fft and came up with a nice plot I thought I'd share:

<img width="574" alt="screen shot 2017-01-18 at 4 21 25 pm" src="https://cloud.githubusercontent.com/assets/713251/22088610/32193d58-dd9a-11e6-9b09-1816613e325f.png">

So a 20x speedup out of the box -- that number includes memory copy time:

``` python
import time
import numpy as np
import pylab as plt

from bifrost.GPUArray import GPUArray
from bifrost.ring import Ring
from bifrost.fft import fft, ifft
from bifrost.libbifrost import _bf, _string2space

dsize = 1
t_gpu   = []
t_np    = []
speedup = []
d_sizes = []

for ii in range(27):
    dsize *= 2
    d_sizes.append(dsize)
    
    # Generate data
    input_data  = GPUArray(shape=dsize, dtype=np.complex64)
    output_data = GPUArray(shape=dsize, dtype=np.complex64)
    d = np.random.random(dsize)
    
    # Copy to GPU, FFT, copy back
    t1 = time.time()
    input_data.set(d)
    input_array  = input_data.as_BFarray()
    output_array = output_data.as_BFarray()
    fft(input_array, output_array)
    dd = output_data.get()
    t2 = time.time()
    print "GPU: ", t2 - t1
    t_gpu.append((t2 - t1))
    
    # Numpy FFT
    t01 = time.time()
    dd_np = np.fft.fft(d)
    t02 = time.time()
    print "CPU: ",t02 - t01
    t_np.append((t02 - t01))
    speedup.append(float(t02 - t01) / (t2 - t1))

plt.subplot(2,1,1)
plt.loglog(d_sizes, t_np, label='Numpy FFT',    c='#333333')
plt.loglog(d_sizes, t_gpu, label='Bifrost FFT', c='#cc0000')
plt.ylabel('Time [s]')
plt.legend(loc=2)
plt.subplot(2,1,2)
plt.semilogx(d_sizes, speedup, c='#333333')
plt.ylabel("Speedup")
plt.xlabel('Array size')
plt.show()
```

To get to grips with how things fit together, I wanted to take the `fft` function and convert it into a block. Here's my attempt, based on some other blocks in the library:

```python
import numpy as np
import pylab as plt

from bifrost.GPUArray import GPUArray
from bifrost.ring import Ring
from bifrost.fft import fft, ifft
from bifrost.libbifrost import _bf, _string2space
from bifrost.block import Pipeline, NumpyBlock, NumpySourceBlock
from bifrost.copy_block import CopyBlock

import time

from bifrost.pipeline import TransformBlock

class DanFFTBlock(TransformBlock):
    def __init__(self, iring, space, *args, **kwargs):
        super(DanFFTBlock, self).__init__([iring], *args, **kwargs)
        self.orings = [self.create_ring(space=space)]
        
        self.input_data  = GPUArray(shape=1024, dtype=np.complex64)
        self.output_data = GPUArray(shape=1024, dtype=np.complex64)
        
    def on_sequence(self, iseqs):
        ohdr = deepcopy(iseqs[0].header)
        return [ohdr], [None]
        
    def on_data(self, ispans, ospans):
        input_array  = self.input_data.as_BFarray()
        output_array = self.output_data.as_BFarray()
        
        input_data.set(ispans[0].data)
        fft(input_array, output_array)
        dd = output_data.get()
        ospans[0].data = dd

# Our simple test-bench
def generate_test_vectors():
    for ii in xrange(10):
        yield np.ones(1024)

def validate_test_vectors(x):
    #v = np.arange(0, arr_size, 1, dtype='complex64')
    #assert np.allclose(x, v) 
    print x.shape
        
blocks = [
  (NumpySourceBlock(generate_test_vectors), {'out_1': 'raw'}),
  (DanFFTBlock({'in_1': 'raw',   'out_1': 'fft0'})),
  #(NumpyBlock(np.fft.fft),  {'in_1': 'raw',   'out_1': 'fft0'}),
  (NumpyBlock(validate_test_vectors, outputs=0), {'in_1': 'fft0'})
]

Pipeline(blocks).main()
```

It's not quite there, I think because the ring dictionary syntax is different to the iring, oring syntax (if that makes sense). What is the minimum change to this code to get it to run using `Pipeline`? And how would this change with TF syntax?

Thanks
Danny

**Comment by benbarsdell** [comment]
Great results!

On the DanFFTBlock, I think you're mixing old and new block styles. The on_data and on_sequence methods are part of the block definition in the new pipeline.py (TF syntax), while the rest is based on the older block.py.

**Comment by telegraphic** [comment]
Thanks, I've now got a basic 'working' pipeline, where I generate dummy data in one block, do an fft in another block, and then print the output in another block. Some questions below, the answers of which I'll start writing up to make some documentation of my adventure into Asgaard.

Here's my code for the simplest pipeline I could come up with:

```python
import numpy as np
import time

from bifrost.GPUArray import GPUArray
from bifrost.fft import fft, ifft
import bifrost.pipeline as bfp


class DanFakeFile(object): 
    """ This is instead of needing an actual file / stream to read from """
    def __init__(self, n_iter):
        super(DanFakeFile, self).__init__()
        self.n_iter = n_iter       # Maximum number of read iterations before closing
        self.iter_cnt = 0          # Iteration counter
                       
    def read(self, n):
        self.iter_cnt += 1
        if self.iter_cnt >= 100:
            self.__exit__(0, 0, 0)
        else:
            print self.iter_cnt
            return np.random.random(n)
        
    def __enter__(self):
        return self

    def __exit__(self, type, value, tb):
        pass


class DanSourceBlock(bfp.SourceBlock):
    def __init__(self, sourcenames, gulp_nframe, *args, **kwargs):
        super(DanSourceBlock, self).__init__(sourcenames, gulp_nframe, *args, **kwargs)
        self.space = 'auto'
        
    def create_reader(self, sourcename):
        return DanFakeFile(n_iter=10)
         
    def on_sequence(self, ireader, sourcename):        
        
        ohdr = {'name': sourcename,
                'time_tag' : 1,
                '_tensor': {
                        'dtype':  'f32',
                        'shape':  [-1, 1024],
                        'labels': 'time',
                        'scales':  1,
                        'units':   's'
                        },    
                    }
                    
        return [ohdr]
        
    def on_data(self, reader, ospans):
        ospan  = ospans[0]
        indata = reader.read(ospan.shape[0])
        nframe = indata.shape[0]
        ospan.data[:nframe] = indata
        return [nframe]


class DanFFTBlock(bfp.TransformBlock):
    def __init__(self, iring, space, *args, **kwargs):
        super(DanFFTBlock, self).__init__([iring], *args, **kwargs)
        self.orings = [self.create_ring(space=space)]
        
        self.input_data  = GPUArray(shape=1024, dtype=np.complex64)
        self.output_data = GPUArray(shape=1024, dtype=np.complex64)
        
    def on_sequence(self, iseqs):
        ohdr = iseqs[0].header
        return [ohdr], [None]
        
    def on_data(self, ispans, ospans):
        input_array  = self.input_data.as_BFarray()
        output_array = self.output_data.as_BFarray()
                
        temp_array_i_shouldnt_need = np.zeros_like(ispans[0].data)
        for ii, span_data in enumerate(ispans[0].data):
            self.input_data.set(span_data)
            fft(input_array, output_array)
            dd = self.output_data.get()
            temp_array_i_shouldnt_need[ii] = dd
        ospans[0].data.set(temp_array_i_shouldnt_need)
     


class DanPrintBlock(bfp.TransformBlock):
    def __init__(self, iring, space, *args, **kwargs):
        super(DanPrintBlock, self).__init__([iring], *args, **kwargs)
        
    def on_sequence(self, iseqs):
        ohdr = iseqs[0].header
        return [ohdr], [None]
        
    def on_data(self, ispans, ospans):
        print(ispans[0].data)


if __name__ == '__main__':

    filenames   = ['cat', 'dog', 'chicken', 'wolf']
    b_generator = DanSourceBlock(filenames, 1, core=0)
    b_fft       = DanFFTBlock(b_generator.orings[0], space='cuda', core=1)
    b_out       = DanPrintBlock(b_generator.orings[0], space='cuda', core=2)
    
    pipeline = bfp.get_default_pipeline()
    
    print(pipeline.dot_graph())

    pipeline.run()
    print "All done"
```

Some questions:

1) This crashes on the last iteration. How do I gracefully exit?
```
  File "test_fft_pipeline.py", line 55, in on_data
    nframe = indata.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'
```
2)  The `_tensor` and `time_tag` header keywords appear to be mandatory. Is this the case? What should I be doing with the time tag? Is the idea that this is set once (and only once) in the `SourceBlock` once, then propagated automatically?

3) My `DanFFTBlock` needed a temp array as I couldn't index direct into `ospans[0].data`. How should I better handle this?

4) Can we get a `bpf.SinkBlock`? This can be exactly the same as the TransformBlock, it'd just be nice conceptually to have Source -> Transform -> Sink

5) I'm currently not doing anything with the headers, or really doing anything with on_sequence. How should I better handle this? My list of animal filenames isn't really doing anything, but seems required.

**Comment by benbarsdell** [comment]
> This crashes on the last iteration. How do I gracefully exit?

I think your reader needs to return a zero-length array instead of calling `self.__exit__` and returning None.

> The _tensor and time_tag header keywords appear to be mandatory. Is this the case? What should I be doing with the time tag? Is the idea that this is set once (and only once) in the SourceBlock once, then propagated automatically?

Yes these are currently mandatory, although I admit I'm not completely satisfied with their names etc. yet. The time_tag one should probably be optional; I'll see if I can fix this in ring2.py. They should be propagated by copying the headers inside each on_sequence function.

> My DanFFTBlock needed a temp array as I couldn't index direct into ospans[0].data. How should I better handle this?

Yes this looks pretty bad. I don't fully understand what the problem is (could you elaborate on any errors you saw?), but it may improve once the new ndarray is integrated.

> Can we get a bpf.SinkBlock? This can be exactly the same as the TransformBlock, it'd just be nice conceptually to have Source -> Transform -> Sink

Yep this is on my todo list.

> I'm currently not doing anything with the headers, or really doing anything with on_sequence. How should I better handle this? My list of animal filenames isn't really doing anything, but seems required.

Headers and on_sequence are really for generating and interpreting metadata. E.g., some blocks need to change the shape/dtype/other metadata so that their output can be interpreted correctly. You should be able to get away with little/no metadata, but the more there is the 'smarter' the pipeline becomes. E.g., see fdmt_block.py, which manages lots of array metadata including dimension scales and units.

Note that `ohdr = iseqs[0].header` should be `ohdr = deepcopy(iseqs[0].header)` to avoid accidentally changing the input header. I may be able to make this safe automatically, but for now a deepcopy is recommended.

**Comment by telegraphic** [comment]
Thanks Ben,

Here's the error I get:
```
  File "test_bifrost.py", line 99, in on_data
    ospans[0].data[0] = dd
TypeError: 'GPUArray' object does not support item assignment
```
where dd shape is (524288,)  and ospans[0].data shape is (1, 524288), for example

**Comment by telegraphic** [comment]
I think you can ignore the above right now, I've made progress today! 

New question: how would you implement an accumulator, that only needs to output data every Nth integration? Here's my accumulator block, which seems to work, but outputs every cycle:

```
class AccumulateBlock(bfp.TransformBlock):
    def __init__(self, iring, space, *args, **kwargs):
        super(AccumulateBlock, self).__init__([iring], *args, **kwargs)
        self.acc_data = None
        self.counter = 0
        
    def on_sequence(self, iseqs):
        ohdr = deepcopy(iseqs[0].header)
        self.acc_data = np.expand_dims(np.zeros(ohdr['_tensor']['shape'][1:]), axis=0)
        
        return [ohdr], [None]
        
    def on_data(self, ispans, ospans):
        t1 = time.time()
        self.acc_data += ispans[0].data
        self.counter += 1
        #print(self.acc_data[0])
        t2 = time.time()
        print "Accum time:         %2.2fs" % (t2 - t1)
        
        ospans[0].data[:1] = self.acc_data
        return [1]
```

**Comment by benbarsdell** [comment]
Returning 0 frames from on_data when accumulating should do the trick
(although I haven't tested it before).

**Comment by telegraphic** [comment]
That does appear to work! Closing this thread as most questions answered.

**Comment by benbarsdell** [comment]
FYI, https://github.com/ledatelescope/bifrost/commit/d8a548fb746ae8fe2022dcf11c9c66aae6e30b8f adds a SinkBlock specialisation.
