### ISSUE TITLE
How do I control ring size?

### ISSUE THREAD

**Issue by telegraphic** [ledatelescope/bifrost#68]
I can't figure out how to do this in the TF syntax, or even how to do this in ring2.py. I keep running out of memory on the GPU, slowly, as the pipeline progresses, so need some manual control (at least, I think it's because the ring buffers keep getting bigger?)

**Comment by benbarsdell** [comment]
Ring size is determined by the `gulp_nframe` and `buffer_factor` arguments to a Block. Currently `buffer_factor` defaults to 3.

What you describe sounds like a memory leak, which is not supposed to happen. Do you have a simple repro script?

**Comment by telegraphic** [comment]
will look into this shortly, working on other things. It is possible/likely/near certain that I munged something in my CUDA kernel.

**Comment by telegraphic** [comment]
Closing for now
