### ISSUE TITLE
Two minor things

### ISSUE THREAD

**Issue by telegraphic** [ledatelescope/bifrost#72]
1) Need to add version.py to git repo, setup.py fails without it
2) Suggestion: `pipeline.py` to start threads with block names? I think this is as simple as:

```python
class Pipeline(BlockScope):
	def __init__(self, **kwargs):
		super(Pipeline, self).__init__(**kwargs)
		self.blocks = []
	def as_default(self):
		return PipelineContext(self)
	def run(self):
		print "Launching %i blocks" % len(self.blocks)
		threads = [threading.Thread(target=block.run, name=block.name) for block in self.blocks]
		for thread in threads:
			thread.start()
		print "Waiting for blocks to finish"
		for thread in threads:
			thread.join()
	...
```

**Comment by benbarsdell** [comment]
1. Run `make` to generate version.py
2. Sounds good to me.

**Comment by benbarsdell** [comment]
1.5: I should probably add a warning message in the script stating this :)

**Comment by benbarsdell** [comment]
1: See also https://github.com/ledatelescope/bifrost/commit/a6ae6f7dde79797a1c017a6e737f482a00c98f86
1.5: https://github.com/ledatelescope/bifrost/commit/65bea36742dc9ff5ca1c242c4d5a8e4fc6e7bd36
2: https://github.com/ledatelescope/bifrost/commit/3cc86975c3905284e3802105c839b767908b3e0b
