### ISSUE TITLE
New FftBlock woes

### ISSUE THREAD

**Issue by telegraphic** [ledatelescope/bifrost#75]
Note: relevant changes in 
https://github.com/ledatelescope/bifrost/tree/dcp_devel/testbench

I am having trouble getting an fft pipeline up & running with the new FftBlock. Here's my testbench:

```python
"""
# test_fft.py

This testbench initializes a simple bifrost pipeline that reads from a binary file,
takes the FFT of the data (on the GPU no less), and then writes it to a new file. 
"""
import os
import glob
import numpy as np
import bifrost.pipeline as bfp
from bifrost.blocks import BinaryFileReadBlock, BinaryFileWriteBlock, FftBlock
from bifrost.blocks import CopyBlock

from scipy.fftpack import fft as scipy_fft

if __name__ == "__main__":
    
    # FFT Parameters
    window_len = 2**18
    n_window   = 32
    
    # Setup pipeline
    filenames   = sorted(glob.glob('testdata/noisy_data*.bin'))
    b_read      = BinaryFileReadBlock(filenames, window_len, 1, 'cf32', core=0)
    
    with bfp.block_scope(core=2, gpu=0):
        b_copy      = CopyBlock(b_read.orings[0], space='cuda')
        b_fft       = FftBlock(b_copy.orings[0], axes=1)
    
    b_out       = CopyBlock(b_fft.orings[0], space='system', core=3)
    b_write     = BinaryFileWriteBlock(b_fft.orings[0], core=3)

    # Run pipeline
    pipeline = bfp.get_default_pipeline()
    print pipeline.dot_graph()
    pipeline.run()

    # Check the output files match the input files
    for filename in filenames:
        try:
            print filename
            
            # Load the input data, do a windowed FFT
            indata  = np.fromfile(filename, dtype='complex64')
            indata  = scipy_fft(indata.reshape(n_window, window_len), axis=1)
            
            # Load the output data and reshape into windowed FFTs
            outdata = np.fromfile('%s.out' % filename, dtype='complex64')
            outdata = outdata.reshape(n_window, window_len)
            
            assert np.allclose(indata, outdata, atol=0.1)
            print "    Input data and output data match."
        except AssertionError:
            print "    Error: input and output data do not match."
            for ii in range(len(indata)):
                print "Window %02i match: %s" % (ii, np.allclose(indata[ii], outdata[ii], atol=0.1))
            print indata[0, 0:10]
            print outdata[0, 0:10]
            print np.max(indata - outdata)

            #raise
        finally:
            print "    Cleaning up..."
            #os.remove(filename + '.out')
            print "    Done."
```

I firstly am confused about block units and scales -- when I add these into my binary reader (https://github.com/ledatelescope/bifrost/blob/dcp_devel/python/bifrost/blocks/binary_io.py) it complains or segfaults.  At one stage it was running, but randomly would not pass the allclose() assertion.

PS: can we relax the requirement on the FftBlock to have scales / units?

**Comment by telegraphic** [comment]
PS: you unfortunately would need to check out the dcp_devel branch to test this out, and run the `generate_test_data.py` in testbench/

**Comment by benbarsdell** [comment]
Thanks for the report, I'll try to look into this this evening. What errors were you getting when trying to add units and scales support? I'll look into relaxing the requirement for these.

And are you seeing bad results from the FFT? I had trouble getting close results on some values when writing the tests; it may actually be a bug somewhere in the backend.

Note that you shouldn't need the `.orings[0]` part in places like this: `CopyBlock(b_read.orings[0]` (let me know if it doesn't work without it though!).

Note also that in this code you should be able to use `bifrost.DataType(self.dtype).as_numpy_dtype()` instead of what you currently have:
https://github.com/ledatelescope/bifrost/blob/dcp_devel/python/bifrost/blocks/binary_io.py#L88

**Comment by benbarsdell** [comment]
OK I found a few minor bugs with the FFT (fixed with https://github.com/ledatelescope/bifrost/commit/644998c9fa10b7f9573428096ff862018c755da6), but I don't think they explain much of what you're seeing.

I've also now made the use of scales/units/labels optional for most blocks (https://github.com/ledatelescope/bifrost/commit/4272055f5626f9f2a6f1cb7620b6586e5e2c2f84).

One problem in your code above is `BinaryFileWriteBlock(b_fft, ...)` (should be `b_out`), which is causing a segfault because the data are still on the GPU.

The really bad news though is that there is a weird race condition occurring whenever more than one block is bound to the same core. At this stage I have no idea why this is happening...
You can try working around it by binding to different cores (or simply not binding). Anything you can find that might shed light on the cause of this problem would be really useful.

**Comment by MilesCranmer** [comment]
If it's relevant, I've had some errors in running the FFT unittests: http://pastebin.com/raw/yBvzxVXw
Everything else seems to be working fine. The missing sigproc_block is odd, though.

**Comment by telegraphic** [comment]
OK, tests now pass :)

Slightly modified code:

```python
"""
# test_fft.py

This testbench initializes a simple bifrost pipeline that reads from a binary file,
takes the FFT of the data (on the GPU no less), and then writes it to a new file. 
"""
import os
import glob
import numpy as np
import bifrost.pipeline as bfp
from bifrost.blocks import BinaryFileReadBlock, BinaryFileWriteBlock, FftBlock
from bifrost.blocks import CopyBlock

from scipy.fftpack import fft as scipy_fft

if __name__ == "__main__":
    
    # FFT Parameters
    window_len = 2**18
    n_window   = 32
    
    # Setup pipeline
    filenames   = sorted(glob.glob('testdata/noisy_data*.bin'))
    b_read      = BinaryFileReadBlock(filenames, window_len, 1, 'cf32', core=0)
    b_copy      = CopyBlock(b_read, space='cuda', core=1, gpu=0)
    b_fft       = FftBlock(b_copy, axes=1, core=2, gpu=0)
    b_out       = CopyBlock(b_fft, space='system', core=3)
    b_write     = BinaryFileWriteBlock(b_out, core=4)

    # Run pipeline
    pipeline = bfp.get_default_pipeline()
    print pipeline.dot_graph()
    pipeline.run()

    # Check the output files match the input files
    for filename in filenames:
        try:
            print filename
            
            # Load the input data, do a windowed FFT
            indata  = np.fromfile(filename, dtype='complex64')
            indata  = scipy_fft(indata.reshape(n_window, window_len), axis=1)
            
            # Load the output data and reshape into windowed FFTs
            outdata = np.fromfile('%s.out' % filename, dtype='complex64')
            outdata = outdata.reshape(n_window, window_len)
            
            assert np.allclose(indata, outdata, atol=0.1)
            print "    Input data and output data match."
        except AssertionError:
            print "    Error: input and output data do not match."
            for ii in range(len(indata)):
                print "Window %02i match: %s" % (ii, np.allclose(indata[ii], outdata[ii], atol=0.1))
            print indata[0, 0:10]
            print outdata[0, 0:10]
            print np.max(indata - outdata)

            #raise
        finally:
            print "    Cleaning up..."
            #os.remove(filename + '.out')
            print "    Done."
```

**Comment by telegraphic** [comment]
argh, accidentally pushed changes to origin instead of my telegraphic branch :/

**Comment by telegraphic** [comment]
reading up on how to undo this...

**Comment by benbarsdell** [comment]
Is this what you're looking to do?
http://stackoverflow.com/a/22683231/7228843
git revert 3d697addaefc8f149bc1afb16db81eb4d312e81c..4ffa7271f991422af262365cbec46b697406ab46

**Comment by telegraphic** [comment]
Thanks, should be reverted

**Comment by benbarsdell** [comment]
Actually it looks like this may not have worked quite right; @MilesCranmer would you be able to double-check the state of things?

**Comment by telegraphic** [comment]
Yep, I can see a testbench folder in the repo now 🆘 . Sorry, that was way too easy :/.

**Comment by MilesCranmer** [comment]
I can force push my forked repo, if need be. It looks to have saved the code right before the changes:

![](http://i.imgur.com/MHoZJrg.png)

The only changes are to the old unit tests and travis file.

**Comment by benbarsdell** [comment]
@telegraphic could probably do this force push to roll things back (as long as no-one else has fetched since); do you agree @MilesCranmer?
git push -f origin 3d697addaefc8f149bc1afb16db81eb4d312e81c:master

**Comment by telegraphic** [comment]
Ok with me

**Comment by MilesCranmer** [comment]
BTW, it looks like you may have needed an `-m` to undo a merge commit? [SO thread](http://stackoverflow.com/questions/7099833/how-to-revert-a-merge-commit-thats-already-pushed-to-remote-branch)

**Comment by MilesCranmer** [comment]
@benbarsdell Would that work even though it's a merge he's undoing?

**Comment by benbarsdell** [comment]
I've never done it before, but it should hard reset things back to the specified commit (I got it from here: http://stackoverflow.com/a/588615/7228843).

**Comment by MilesCranmer** [comment]
The only thing is that the merge added commits before that one, e.g., bb4f2606f2c860f9c8518bbb7c2e29a25b7b6cbf. So maybe only rolling back to 3d697addaefc8f149bc1afb16db81eb4d312e81c would not reset the commits inserted into the history?

**Comment by benbarsdell** [comment]
I think it will work actually. A better way to put it might be:
git reset --hard 3d697addaefc8f149bc1afb16db81eb4d312e81c
[Look at git log and check that it looks as desired, ending in Miles' last commit]
git push -f origin master

Resetting to the commit hash before the merge means there can't be any other commits in there, else the hash would have changed.

**Comment by benbarsdell** [comment]
If there are no objections, I can do this reset and force push.

**Comment by MilesCranmer** [comment]
Fine with me!

**Comment by benbarsdell** [comment]
Done.
@telegraphic you may need to run this on your local copy too to get back in sync.
git reset --hard 3d697addaefc8f149bc1afb16db81eb4d312e81c
