### ISSUE TITLE
make should exit after error

### ISSUE THREAD

**Issue by MilesCranmer** [ledatelescope/bifrost#85]
This should probably be simple to fix. This issue is just a reminder to make sure we've fixed it.

When I built Bifrost, forgetting to install exuberant-ctags, I got the (expected) error:
```
/bin/sh: 1: ctags: not foundn
*************************************
ERROR: Please install exuberant-ctags
*************************************
```

However, unexpectedly (?), the make process continued and copied all the python directories into the build directory, burying the above error. The make still exited with an error, though.

So, I think that make should exit when that error occurs.

**Comment by benbarsdell** [comment]
This problem stems from independent targets being built in parallel; errors only cause sequential dependencies to stop.

I've added a dependency to the python target so that it won't run until libbifrost is fully built, which solves the problem here.

**Comment by MilesCranmer** [comment]
Thanks, Ben! That was quick 👍
