### ISSUE TITLE
Clean-up: Have a dependency-only image hosted on docker hub

### ISSUE THREAD

**Issue by MilesCranmer** [ledatelescope/bifrost#87]
Since the dependencies for Bifrost have remained constant for a while, it seems like it would be more efficient to have a Dockerfile containing just the dependencies (maybe mirrored in another branch so you can pull from docker hub with `docker pull ledatelescope/bifrost:deps`).

The main Dockerfile would then just have to contain `FROM ledatelescope/bifrost:deps`, which would make it shorter, and would also mean that local builds would happen faster (you could just pull the dependencies and go). This would make the travis-ci tests faster too, as travis wouldn't have to keep re-building the entire dependency stack.

Docker hub has auto-building functionality on each commit, so we would still see the most up-to-date binaries being pulled.

**Comment by benbarsdell** [comment]
I've been working on some Dockerfile refactoring along these lines that I'll push soon.

**Comment by benbarsdell** [comment]
See PR https://github.com/ledatelescope/bifrost/pull/92
