### ISSUE TITLE
bfMap reduction on axis

### ISSUE THREAD

**Issue by telegraphic** [ledatelescope/bifrost#93]
Can bfMap do things like average/sum over an axis? If so, can I please request some example syntax strings?

**Comment by benbarsdell** [comment]
It can be done. Note though that reducing over a fast axis (e.g., the inner dimension of an array) will probably be very inefficient. Reducing over an outer dim (like the example below) should be OK.
```
import bifrost as bf
import numpy as np

data = bf.asarray(np.random.random(size=(300,64)).astype(np.float32), space='cuda')
mean = bf.empty(64, 'f32', 'cuda')
bf.map("""
    mean = 0;
    for( int i=0; i<data.shape(0); ++i ) {
        mean += data(i,j);
    }
    mean /= data.shape(0);""",
       mean.shape, 'j', mean=mean, data=data)
print mean
```

**Comment by benbarsdell** [comment]
Closing this now that commit https://github.com/ledatelescope/bifrost/commit/d0c9ef9269eb5d0c61a695500fe89bd723fdf7f3 has added bfReduce/bf.reduce/ReduceBlock for doing axis reductions (although custom kernels are used instead of bfMap).
