### ISSUE TITLE
bfmap.rst out of date

### ISSUE THREAD

**Issue by ewanbarr** [ledatelescope/bifrost#99]
On master the bfmap.rst docs are out of date as it looks like the map interface has changed.

For example, if I follow the docs:

```
In [24]: bf.map("c = a + b", c=c, a=a, b=b)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-107ca22ae66a> in <module>()
----> 1 bf.map("c = a + b", c=c, a=a, b=b)

TypeError: map() got an unexpected keyword argument 'c'
```

**Comment by MilesCranmer** [comment]
Thanks for pointing this out @ewanbarr. The change was posted in #95 (but the docs weren't updated).
I'll update the docs straight away.

**Comment by MilesCranmer** [comment]
It *should* be fixed now: http://ledatelescope.github.io/bifrost/bfmap.html.
Let me know if you notice anything else not up-to-date.

Thanks again,
Miles
